permalink: /:title.html
title: James Zhu
description: "James Zhu's Blog"
keywords: James
production_url: http://zhujian0805.github.io
pygments: false
markdown: redcarpet
redcarpet:
  extensions: ["tables","with_toc_data", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
author :
  name : James Zhu
  github : zhujian0805
  email: zhujian0805@gmail.com
  linkedin: zhujian0805
disqus_shortname: zhujian0805
analytics: UA-39542235-1
